### PR TITLE
[PDI-16923] - a typo bug in kettle-sdk-embedding-samples

### PR DESCRIPTION
**Pull request by CravoBranco**
* Fixed additional typos.

### CODE REVIEW

**Comment by CravoBranco** [comment]
This PR contains some additional fixes that were requested by the colleague who validated PDI-16293.
Therfeore, @pentaho-lmartins , @duarteteixeira , @mchen-len-son , @mbatchelor please review and merge if it's all ok.

**Comment by mchen-len-son** [comment]
@CravoBranco can you please take a look if we can fix the failing tests (or make them deterministic) in a reasonable time?
thank you.

**Comment by CravoBranco** [comment]
@mchen-len-son , the tests are now passing successfully.
The fail seems to happen when the connection destination is not available or the port is busy. Once it is released, then the test pass successfully as happened.

**Comment by mchen-len-son** [comment]
Maybe this line is too restrictive
https://github.com/pentaho/pdi-sdk-plugins/blob/master/kettle-sdk-embedding-samples/src/test/java/org/pentaho/di/sdk/samples/carte/BaseCarteServletTest.java#L125

If it doesn't help I leave it up to @pentaho-lmartins to merge this one, as I don't have permissions here

**Comment by CravoBranco** [comment]
@mchen-len-son , the broken test is now gone :)

**Pull request merged**
